# Generated by Django 3.0 on 2020-03-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generative_model', '0002_auto_20200318_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generativemodel',
            old_name='sdf',
            new_name='pdb',
        ),
        migrations.AddField(
            model_name='generativemodel',
            name='iterations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='generativemodel',
            name='residue_name',
            field=models.CharField(default='LIG', max_length=3),
        ),
    ]
