# Generated by Django 3.0 on 2020-03-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analogs_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsmodel',
            name='email',
            field=models.CharField(default='...@gmail.com', max_length=100),
        ),
    ]
